### Scripts ###
.activate_mise: &activate_mise
  - mise install
  - eval "$(mise env)"

.update_nuget_source_ro: &update_nuget_source_ro
  - dotnet nuget update source JFrogNuGetProxy --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text
  - dotnet nuget update source JFrogViciOne --configfile NuGet.Config -u $NuGet_User_JFrog -p $NuGet_PW_JFrog --store-password-in-clear-text

.update_nuget_source_rw: &update_nuget_source_rw
  - dotnet nuget update source JFrogViciOne --configfile NuGet.Config -u $NuGet_User_RW_JFrog -p $NuGet_PW_RW_JFrog --store-password-in-clear-text

.rule_tag: &rule_tag
  if: "$CI_COMMIT_TAG"

.rule_default_branch: &rule_default_branch
  if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

.rule_mr: &rule_mr
  if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

.rule_web: &rule_web
  if: '$CI_PIPELINE_SOURCE == "web"'

.rules: &rules
  - *rule_tag
  - *rule_default_branch
  - *rule_mr
  - *rule_web

.rules_manual: &rules_manual
  - <<: *rule_tag
    when: manual
    allow_failure: true
  - <<: *rule_default_branch
    when: manual
    allow_failure: true
  - <<: *rule_mr
    when: manual
    allow_failure: true
  - <<: *rule_web
    when: manual
    allow_failure: true

.install_npm_packages: &install_npm_packages
  - npm ci

.run_eslint: &run_eslint
  - npm run lint

### Defaults ###
variables:
  IMAGE_NAME: registry.gitlab.com/vicione-oss/tooling/base-image:vicione-latest
  RUNNER_TAG: saas-linux-small-amd64

stages:
  - build
  - test
  - pack
  - push
  - publish

### CI Components ###
include:
  ### Version calculation
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/components/version/version-calc@v1.2.0
  ### Restore
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-restore@v2.6.0
    inputs:
      image: ${IMAGE_NAME}
      rules: *rules
      before_script:
        - *activate_mise
        - *update_nuget_source_ro
        - *install_npm_packages
      tags:
        - ${RUNNER_TAG}
  ### Renovate configuration validation
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/components/renovate/configuration-validation@v1.0.0
    inputs:
      rules: *rules
      tags:
        - ${RUNNER_TAG}
  ### Build
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-build@v2.6.0
    inputs:
      image: ${IMAGE_NAME}
      rules: *rules
      before_script:
        - *activate_mise
        - *update_nuget_source_ro
        - 'echo "Version: ${Version:-notAssigned}"'
      tags:
        - ${RUNNER_TAG}
  ### Test
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-test@v2.6.0
    inputs:
      name: "dotnet Test"
      image: ${IMAGE_NAME}
      rules: *rules
      before_script:
        - *activate_mise
        - *update_nuget_source_ro
      tags:
        - ${RUNNER_TAG}
      filter: '/[Category!=Playwright]'
      coverage: true
  ### Pack
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-pack@v2.6.0
    inputs:
      image: ${IMAGE_NAME}
      rules: *rules_manual
      before_script:
        - *activate_mise
        - 'echo "PackageVersion: ${PackageVersion:-notAssigned}"'
        - 'export PREVENT_BUILD_PROJECT_REFERENCES_WHEN_TENEKON_IS_USED=true'
      tags:
        - ${RUNNER_TAG}
  ### Push
  - component: $CI_SERVER_FQDN/vicione-oss/tooling/dotnet-component/dotnet-nuget-push@v2.6.0
    inputs:
      stage: "push"
      image: ${IMAGE_NAME}
      source: "JFrogViciOne"
      filename_pattern: "*/src/*"
      rules: *rules
      before_script:
        - *activate_mise
        - *update_nuget_source_rw
      tags:
        - ${RUNNER_TAG}

### ESLint ###
ESLint:
  stage: build
  image: ${IMAGE_NAME}
  needs: ["dotnet Build"]
  before_script:
    - *activate_mise
    - *update_nuget_source_ro
    - *install_npm_packages
  script:
    - *run_eslint
  rules: *rules
  tags:
    - ${RUNNER_TAG}

### GitLab Pages
Publish Pages:
  stage: publish
  image: ${IMAGE_NAME}
  pages: true
  needs: ["dotnet Test"]
  before_script:
    - *activate_mise
    - *update_nuget_source_ro
    - *install_npm_packages
  script:
    - dotnet publish samples/Client -c Release -o artifacts
    - mkdir public
    - cp -R artifacts/wwwroot/* public
    - echo "Publish Pages on \"$CI_PAGES_URL\""
  rules: *rules_manual
