<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!--
      Strangely, 'dotnet pack' executed in solution root includes this project even though 'IsPackable' is set to false
      in Directory.Build.props, which results in a warning. We suppress the warning with the following property.
    -->
    <WarnOnPackingNonPackableProject>false</WarnOnPackingNonPackableProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
