using System.Runtime.CompilerServices;
using System.Security.Cryptography;
using ViciOne.Ui.Blazor.Components.LoadingSpinner.Factories;
using ViciOne.Ui.Blazor.Components.LoadingSpinner.Models;
using LoadingSpinnerComponent = ViciOne.Ui.Blazor.Components.LoadingSpinner.Components.LoadingSpinner;

namespace Shared.Pages.LoadingSpinner;

public sealed partial class LoadingSpinnerPage
{
    private LoadingSpinnerComponent? _loadingSpinner;
    private bool _loadingSpinnerVisible = true;
    private TimedMessage[] _timedMessages = [];
    private bool _loadingSpinnerWithChildContent;

    private static TimedMessage CreateNewRandomMessage([CallerMemberName] string caller = "")
    {
        var messageDuration = RandomNumberGenerator.GetInt32(-1, 15);
        var messageTimeText = messageDuration < 0 ? "indefinitely" : $"for {messageDuration} seconds";

        return new()
        {
            DisplayDuration = messageDuration,
            Message = $"This message was generated by {caller} and will be displayed {messageTimeText}."
        };
    }

    private void OnDisplayNewMessageButtonClicked()
        => _loadingSpinner?.DisplayMessage(CreateNewRandomMessage());

    private void OnEnqueueNewMessageButtonClicked()
        => _loadingSpinner?.QueueMessage(CreateNewRandomMessage());

    private void OnNextMessageButtonClicked()
        => _loadingSpinner?.NextMessage();

    private void OnToggleTimedMessagesChanged(bool enabled)
    {
        if (!enabled)
        {
            _timedMessages = [];
            _loadingSpinner?.ClearMessageQueue();
            return;
        }

        _timedMessages = [
            new()
            {
                DisplayDuration = 2,
                Message = "This message will be displayed when the spinner gets visible.",
            },
            TimedMessageFactory.CreateGap(3),
            new()
            {
                DisplayDuration = 5,
                Message = "This message will be displayed after 5sec.",
            },
            new()
            {
                DisplayDuration = 2,
                Message = "This message will be displayed after 10sec and be gone 2sec later.",
            },
            TimedMessageFactory.CreateGap(3),
            new()
            {
                DisplayDuration = 3,
                Message = "This message will be displayed after 15sec and ...",
            },
            TimedMessageFactory.CreateGap(2),
            new()
            {
                DisplayDuration = 3,
                Message = "... will be followed by a smooth transitioning to another message.",
            },
            TimedMessageFactory.CreateGap(2),
            new()
            {
                DisplayDuration = -1,
                Message = "This message will be displayed after 25sec and will stay forever.",
            },
        ];
    }
}
