<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Bunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ViciOne.Ui.Blazor.Components\ViciOne.Ui.Blazor.Components.csproj" />
    <ProjectReference Include="..\..\src\ViciOne.Ui.Blazor.Components.TestingHelpers\ViciOne.Ui.Blazor.Components.TestingHelpers.csproj" />
  </ItemGroup>

</Project>
